//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::courses::Entity as Courses;
pub use super::orders::Entity as Orders;
pub use super::schedules::Entity as Schedules;
pub use super::teachers::Entity as Teachers;
pub use super::users::Entity as Users;
