//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "schedules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub course_id: i32,
    pub schedule_id: i32,
    pub shop_name: String,
    pub shop_id: i32,
    pub shop_type: i32,
    pub max_users: i32,
    pub start: String,
    pub end: String,
    pub ymd: i32,
    pub course_name: String,
    pub week_day: String,
    pub description: String,
    pub difficulty_level: i32,
    pub course_length: i32,
    pub course_type_tag: String,
    pub teacher_username: String,
    pub teacher_gender: i32,
    pub teacher_score: Option<Decimal>,
    pub teacher_id: i32,
    pub teacher_avatar: String,
    pub create_time: Option<i32>,
    pub update_time: Option<i32>,
    pub start_fmt: String,
    pub end_fmt: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
